name: Release

on:
    push:
        tags:
        - 'v*'

defaults:
    run:
        shell: bash

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release
        -   name: Make
            working-directory: build
            run: cmake --build .
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-linux-glibc
                path: build/libsa.so
                if-no-files-found: error
    
    macos:
        name: Mac
        runs-on: macos-11
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release
        -   name: Make
            working-directory: build
            run: cmake --build .
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-macos
                path: build/libsa.dylib
                if-no-files-found: error
    
    windows:
        name: Windows
        runs-on: windows-2022
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release
        -   name: Make
            working-directory: build
            run: cmake --build . --config Release
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-win-x64
                path: build/Release/sa.dll
                if-no-files-found: error
    
    create_release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: [ linux, macos, windows ]
        steps:
        -   uses: actions/download-artifact@v2
            with:
                path: artifacts
        -   name: Download Public Header
            run: |
                curl -H "Authorization: token ${{ github.token }}" \
                  -H 'Accept: application/vnd.github.v3.raw' \
                  -o artifacts/sa.h \
                  -L ${{ github.api_url }}/repos/${{ github.repository }}/contents/sa.h?ref=${{ github.ref_name }}
        -   name: Create Release
            uses: softprops/action-gh-release@v0.1.12
            with:
                name: libsa
                files: |
                    artifacts/**
