name: Integration

on:
    pull_request:
        branches:
        - '**'
        - '!gh-pages'
    push:
        branches:
        - '**'
        - '!gh-pages'

defaults:
    run:
        shell: bash

jobs:
    skip_check:
        name: Skip Run Check
        continue-on-error: true
        runs-on: ubuntu-20.04
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
            is_not_release: ${{ steps.release_check.outputs.is_not_release }}
        steps:
        -   name: Check if duplicate action
            id: skip_check
            uses: fkirc/skip-duplicate-actions@master
            with:
                skip_after_successful_duplicate: 'true'
                paths_ignore: '["**/README.md", ".idea/**", ".editorconfig", ".git*", "docs/**", ".github/**"]'
        -   name: Full checkout
            if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
        -   name: Check if should be release / has version tag
            id: release_check
            if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
            run: |
                git describe --exact-match --match='v*' --abbrev=0 --tags ${{ github.sha }} 2>/dev/null \
                || echo "::set-output name=is_not_release::true"

    linux:
        name: Linux
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release
        -   name: Make
            working-directory: build
            run: cmake --build .
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-linux-glibc
                path: build/libsa.so
                if-no-files-found: error
    
    macos:
        name: Mac
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: macos-11
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release
        -   name: Make
            working-directory: build
            run: cmake --build .
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-macos
                path: build/libsa.dylib
                if-no-files-found: error
    
    windows:
        name: Windows
        needs: skip_check
        if: ${{ (needs.skip_check.outputs.should_skip != 'true') && (needs.skip_check.outputs.is_not_release == 'true') }}
        runs-on: windows-2022
        steps:
        -   uses: actions/checkout@v2
        -   name: Configure
            run: |
                mkdir build
                cd build
                cmake .. -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release
        -   name: Make
            working-directory: build
            run: cmake --build . --config Release
        -   name: Test
            working-directory: build
            run: ctest
        -   uses: actions/upload-artifact@v2
            name: Artifact
            with:
                name: libsa-win-x64
                path: build/Release/sa.dll
                if-no-files-found: error
