name: build

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Configure
              run: |
                  mkdir build
                  cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Release
            - name: Make
              working-directory: build
              run: cmake --build .
            - name: Test
              working-directory: build
              run: ctest
            - uses: actions/upload-artifact@v2
              name: Artifact
              with:
                  name: libsa-linux-glibc
                  path: build/libsa.so
                  if-no-files-found: error

    macos:
        name: Mac
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v2
            - name: Configure
              run: |
                  mkdir build
                  cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Release
            - name: Make
              working-directory: build
              run: cmake --build .
            - name: Test
              working-directory: build
              run: ctest
            - uses: actions/upload-artifact@v2
              name: Artifact
              with:
                  name: libsa-macos
                  path: build/libsa.dylib
                  if-no-files-found: error

    windows:
        name: Windows
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v2
            - name: Configure
              run: |
                  mkdir build
                  cd build
                  cmake .. -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES=Release
            - name: Make
              working-directory: build
              run: cmake --build . --config Release
            - name: Test
              working-directory: build
              run: ctest
            - uses: actions/upload-artifact@v2
              name: Artifact
              with:
                  name: libsa-win-x64
                  path: build/Release/sa.dll
                  if-no-files-found: error
