name: Documentation

on:
    push:
        tags:
        - 'v*'
        branches:
        - 'main'

    workflow_call:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

defaults:
    run:
        shell: bash

jobs:
    generate_docs:
        name: Generate Documentation
        runs-on: ubuntu-22.04
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
        -   name: Install python3-clang & essential libs
            run: sudo apt install python3-clang-14 build-essential
        -   name: Set up Python environment
            uses: actions/setup-python@v3
            with:
                python-version: 3.9
                cache: 'pip'
                cache-dependency-path: 'docs/requirements.txt'
        -   name: Install Sphinx & required modules
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            working-directory: ./docs
        -   name: Build documentation
            run: |
                sphinx-multiversion source build/html
            working-directory: ./docs
        -   name: Create index
            shell: bash
            working-directory: ./docs/build/html/
            env:
                filename: index.html
            run: |
                echo '<html><head><meta http-equiv="Refresh" content="0; url=' > $filename
                echo "'/libsa/main/'" >> $filename
                echo '" /></head><body>Redirecting</body></html>' >> $filename
                touch .nojekyll
                ls -la
        -   name: Commit documentation
            uses: StirlingLabs/BranchStorageAction@main
            with:
                prune: true
                src: docs/build/html/*
                dst: .
                storage-branch: gh-pages
