name: Documentation

on:
    push:
        tags:
        - 'v*'

    workflow_call:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

defaults:
    run:
        shell: bash

jobs:
    generate_docs:
        name: Generate Documentation
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v3
            with:
                ref: ${{ (github.event.inputs || inputs).commit || github.sha }}
        -   name: Generate Documentation
            uses: mattnotmitt/doxygen-action@v1.9.3
        -   name: List Releases
            uses: octokit/request-action@v2.x
            id: list_releases
            with:
                route: GET /repos/${{ github.repository }}/releases
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        -   name: Print releases
            run: |
                cat >releases.json <<'EOL'
                ${{ steps.list_releases.outputs.data }}
                EOL
                jq '.[] | .tag_name,.draft,.prerelease,.published_at,.body' releases.json
        -   name: Commit Documentation
            uses: StirlingLabs/BranchStorageAction@main
            with:
                prune: true
                src: docs/html/*
                dst: ${{ (github.event.inputs || inputs).tag || github.ref_name }}/
                storage-branch: gh-pages
