name: Documentation

on:
    push:
        tags:
        - 'v*'

    workflow_call:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag (Release Version)'
                required: true
                type: string
            commit:
                description: 'Commit Hash'
                required: false
                type: string

defaults:
    run:
        shell: bash

jobs:
    generate_docs:
        name: Generate Documentation
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
            with:
                ref: ${{ (github.event.inputs || inputs).commit || github.sha }}
        -   name: Generate Documentation
            uses: mattnotmitt/doxygen-action@v1.9.3
        -   name: Commit Documentation
            uses: StirlingLabs/BranchStorageAction@main
            with:
                src: docs/html/*
                dst: ${{ (github.event.inputs || inputs).tag || github.ref_name }}/
                storage-branch: gh-pages