name: Integrate

on:
    push:
        branches: [ main, master ]
    
    pull_request:
        branches: [ '**', '!gh-pages', '!coverage ' ]
        types: [ opened, reopened, ready_for_review, synchronize ]
    
    workflow_call:

defaults:
    run:
        shell: bash

jobs:
    skip_check:
        name: Skip Check
        uses: StirlingLabs/.github/.github/workflows/threshold.yaml@main

    metadata:
        name: Collect
        needs: [ skip_check ]
        if: needs.skip_check.outputs.continue == 'true'
        uses: StirlingLabs/.github/.github/workflows/metadata.yaml@main
        with:
            coreName: sa

    build:
        name: Build
        needs: [ skip_check, metadata ]
        if: needs.skip_check.outputs.continue == 'true'
        uses: ./.github/workflows/build.yaml
        with:
            project: ${{ needs.metadata.outputs.project }}

    list:
        name: List Files
        needs: build
        runs-on: ubuntu-latest
        if: needs.skip_check.outputs.continue == 'true'
        steps:
        -   name: list
            run: |
                ls -laR
